/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes.presentacio;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Panell per a la vista de carrega de Kenken.
 * Aquest panell proporciona una interficie d'usuari per a la carrega del contingut Kenken a l'aplicacio.
 * S'utilitza per mostrar opcions i controls relacionats amb la carrega de contingut.
 * 
 * @author marti.
 */
public class CarregarKenkenView extends javax.swing.JPanel {
    private final PrincipalView vistaPrincipal; 
    /**
     * Inicialitza y carrega l'imatge d'una fletxa.
     *
     * @param vistaPrincipal La vista principal de la aplicacio.
     */
    public CarregarKenkenView(PrincipalView vistaPrincipal) {
        this.vistaPrincipal = vistaPrincipal;
        initComponents();
        bJugar1.setEnabled(true);
        
        ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("/images/flecha.png"));
        Image image = imageIcon.getImage(); // Convertir ImageIcon a Image
        Image newImage = image.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Escalar la imagen
        ImageIcon scaledImageIcon = new ImageIcon(newImage);
        bEnrere3.setIcon(scaledImageIcon);
    }
    
    /**
     * 
     * @return El panell on es troba el taulell.
     */
    public JPanel getTaulell(){
        return panel;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bJugar1 = new javax.swing.JButton();
        bEnrere3 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));

        bJugar1.setBackground(new java.awt.Color(0, 102, 102));
        bJugar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        bJugar1.setForeground(new java.awt.Color(255, 255, 255));
        bJugar1.setText("Solucionar");
        bJugar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bJugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugar1ActionPerformed(evt);
            }
        });

        bEnrere3.setBorderPainted(false);
        bEnrere3.setContentAreaFilled(false);
        bEnrere3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEnrere3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnrere3ActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(0, 0, 0));
        panel.setPreferredSize(new java.awt.Dimension(340, 340));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(bJugar1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(bEnrere3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(bEnrere3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bJugar1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bJugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugar1ActionPerformed
        // TODO add your handling code here:
        String kenkenJSON;
        try{
            kenkenJSON = vistaPrincipal.solucionarKenken();
            
            vistaPrincipal.crearKenken2(kenkenJSON, "CarregarKenkenView", "mostrar");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Eror al solucionar el Kenken: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        bJugar1.setEnabled(false);
    }//GEN-LAST:event_bJugar1ActionPerformed

    private void bEnrere3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnrere3ActionPerformed
        // TODO add your handling code here:
        vistaPrincipal.showPanel("JocView");
    }//GEN-LAST:event_bEnrere3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnrere3;
    private javax.swing.JButton bJugar1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
