/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes.presentacio;

import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Panell per a la vista de creacio de sessio.
 * Aquest panell proporciona una interficie d'usuari per a la creacio de sessio en l'aplicacio.
 * es utilitzat per mostrar opcions i controls relacionats amb la creacio de sessio.
 * 
 * @author marti
 */
public class CrearSessioView extends javax.swing.JPanel {
    private final PrincipalView vistaPrincipal; 
    /**
     * Assigna una nova instancia de CrearSessioView i inicialitza els components.
     *
     * @param vistaPrincipal La vista principal de la aplicacio.
     */
    public CrearSessioView(PrincipalView vistaPrincipal) {
        this.vistaPrincipal = vistaPrincipal;
        initComponents();
        
        ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("/images/flecha.png"));
        Image image = imageIcon.getImage(); // Convertir ImageIcon a Image
        Image newImage = image.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Escalar la imagen
        ImageIcon scaledImageIcon = new ImageIcon(newImage);
        bEnrere2.setIcon(scaledImageIcon);
    }
    /**
     * Inicialitza els components de la vista CrearSessioView.
     * Aquesta funcio s'encarrega d'establir valors predeterminats o inicials
     * per a alguns components de la interficie d'usuari.
     */
    public void ini(){
        aContrasenya2.setText("aaaaaaaaaaaaa");
        aContrasenya2.setForeground(new java.awt.Color(153,153,153));
        aNom2.setText("Introdueix el teu nom d'usuari");
        aNom2.setForeground(new java.awt.Color(153,153,153));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tPantalla3 = new javax.swing.JLabel();
        bCrearSessio1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        tNom2 = new javax.swing.JLabel();
        tContrasenya2 = new javax.swing.JLabel();
        aContrasenya2 = new javax.swing.JPasswordField();
        bEnrere2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        aNom2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));

        tPantalla3.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        tPantalla3.setForeground(new java.awt.Color(0, 102, 102));
        tPantalla3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPantalla3.setText("Crear Sessio");
        tPantalla3.setMaximumSize(new java.awt.Dimension(700, 700));
        tPantalla3.setMinimumSize(new java.awt.Dimension(700, 700));
        tPantalla3.setPreferredSize(new java.awt.Dimension(700, 700));

        bCrearSessio1.setBackground(new java.awt.Color(0, 102, 102));
        bCrearSessio1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        bCrearSessio1.setForeground(new java.awt.Color(255, 255, 255));
        bCrearSessio1.setText("Crear Sessio");
        bCrearSessio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCrearSessio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearSessio1ActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        tNom2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tNom2.setText("Nom");

        tContrasenya2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tContrasenya2.setText("Contrasenya");

        aContrasenya2.setBackground(new java.awt.Color(204, 204, 255));
        aContrasenya2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aContrasenya2.setForeground(new java.awt.Color(153, 153, 153));
        aContrasenya2.setText("aaaaaaaaaaaaa");
        aContrasenya2.setBorder(null);
        aContrasenya2.setMaximumSize(new java.awt.Dimension(185, 1));
        aContrasenya2.setMinimumSize(new java.awt.Dimension(185, 1));
        aContrasenya2.setPreferredSize(new java.awt.Dimension(185, 1));
        aContrasenya2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aContrasenya2MousePressed(evt);
            }
        });
        aContrasenya2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aContrasenya2ActionPerformed(evt);
            }
        });

        bEnrere2.setBorderPainted(false);
        bEnrere2.setContentAreaFilled(false);
        bEnrere2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEnrere2.setMaximumSize(new java.awt.Dimension(50, 50));
        bEnrere2.setMinimumSize(new java.awt.Dimension(50, 50));
        bEnrere2.setPreferredSize(new java.awt.Dimension(50, 50));
        bEnrere2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnrere2ActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 2));

        aNom2.setBackground(new java.awt.Color(204, 204, 255));
        aNom2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aNom2.setForeground(new java.awt.Color(153, 153, 153));
        aNom2.setText("Introdueix el teu nom d'usuari");
        aNom2.setBorder(null);
        aNom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aNom2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(bCrearSessio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(116, 116, 116))
            .addComponent(tPantalla3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(bEnrere2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aNom2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tContrasenya2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(248, 248, 248))
                    .addComponent(aContrasenya2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tNom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(304, 304, 304))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator3)
                                .addGap(2, 2, 2))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(bEnrere2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPantalla3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                .addGap(97, 97, 97)
                .addComponent(tNom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aNom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3)
                .addGap(70, 70, 70)
                .addComponent(tContrasenya2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aContrasenya2, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addGap(140, 140, 140)
                .addComponent(bCrearSessio1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearSessio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearSessio1ActionPerformed
        // TODO add your handling code here:
        String nom = aNom2.getText();
        String contra = aContrasenya2.getText();
        if(nom.equals("Introdueix el teu nom d'usuari") || nom.contains(" ")) {
            JOptionPane.showMessageDialog(null, "Introdueix un nom d'usuari sense espais", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (contra.equals("aaaaaaaaaaaaa") || String.valueOf(aContrasenya2.getPassword()).isEmpty() || contra.contains(" ")){
            JOptionPane.showMessageDialog(null, "Introdueix una contrasenya sense espais", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            if(!vistaPrincipal.existsUsuari(nom)){
                try {
                    vistaPrincipal.crearUsuari(nom, contra);
                    vistaPrincipal.setUsuari(nom);
                    vistaPrincipal.showPanel("JocView");
                } catch (Exception e){ 
                    JOptionPane.showMessageDialog(null, "Error al crear l'Usuari: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "L'usuari ja existeix al sistema", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_bCrearSessio1ActionPerformed

    private void aContrasenya2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aContrasenya2MousePressed
        // TODO add your handling code here:
        if(aContrasenya2.getText().equals("aaaaaaaaaaaaa")){
            aContrasenya2.setText("");
            aContrasenya2.setForeground(Color.black);
        }
        if(String.valueOf(aNom2.getText()).isEmpty()){
            aNom2.setText("Introdueix el teu nom d'usuari");
            aNom2.setForeground(Color.gray);
        }
    }//GEN-LAST:event_aContrasenya2MousePressed

    private void aContrasenya2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aContrasenya2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aContrasenya2ActionPerformed

    private void bEnrere2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnrere2ActionPerformed
        // TODO add your handling code here:
        vistaPrincipal.showPanel("MainView");
    }//GEN-LAST:event_bEnrere2ActionPerformed

    private void aNom2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aNom2MousePressed
        if(aNom2.getText().equals("Introdueix el teu nom d'usuari")){
            aNom2.setText("");
            aNom2.setForeground(Color.black);
        }
        if(String.valueOf(aContrasenya2.getPassword()).isEmpty()){
            aContrasenya2.setText("aaaaaaaaaaaaa");
            aContrasenya2.setForeground(Color.gray);
        }
    }//GEN-LAST:event_aNom2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField aContrasenya2;
    private javax.swing.JTextField aNom2;
    private javax.swing.JButton bCrearSessio1;
    private javax.swing.JButton bEnrere2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel tContrasenya2;
    private javax.swing.JLabel tNom2;
    private javax.swing.JLabel tPantalla3;
    // End of variables declaration//GEN-END:variables
}
