/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes.presentacio;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Panell per a la vista d'inici de sessio.
 * Aquest panell proporciona una interficie d'usuari per iniciar sessio en l'aplicacio.
 * 
 * @author marti
 */
public class IniciarSessioView extends javax.swing.JPanel {
    private final PrincipalView vistaPrincipal; 
    /**
     * Assifna una nova instancia de IniciarSessioView  i inicialitza els components.
     *
     * @param vistaPrincipal La vista principal de l'aplicacio.
     */
    public IniciarSessioView(PrincipalView vistaPrincipal) {
        this.vistaPrincipal = vistaPrincipal;
        initComponents();
        
        ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("/images/flecha.png"));
        Image image = imageIcon.getImage(); // Convertir ImageIcon a Image
        Image newImage = image.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Escalar la imagen
        ImageIcon scaledImageIcon = new ImageIcon(newImage);
        bEnrere1.setIcon(scaledImageIcon);
        
    }
    
    /**
     * Inicialitza els components de la vista d'inici de sessio.
     * Aquest metode s'encarrega d'establir valors predeterminats o inicials
     * per a alguns components de la interficie d'usuari.
     */
    public void ini(){
        aContrasenya1.setText("aaaaaaaaaaaaa");
        aContrasenya1.setForeground(new java.awt.Color(153,153,153));
        aNom1.setText("Introdueix el teu nom d'usuari");
        aNom1.setForeground(new java.awt.Color(153,153,153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tPantalla2 = new javax.swing.JLabel();
        bIniciarSessio2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        tNom1 = new javax.swing.JLabel();
        tContrasenya1 = new javax.swing.JLabel();
        aContrasenya1 = new javax.swing.JPasswordField();
        bEnrere1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        aNom1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        tPantalla2.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        tPantalla2.setForeground(new java.awt.Color(0, 102, 102));
        tPantalla2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPantalla2.setText("Iniciar Sessio");

        bIniciarSessio2.setBackground(new java.awt.Color(0, 102, 102));
        bIniciarSessio2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        bIniciarSessio2.setForeground(new java.awt.Color(255, 255, 255));
        bIniciarSessio2.setText("Iniciar Sessio");
        bIniciarSessio2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bIniciarSessio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarSessio2ActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        tNom1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tNom1.setText("Nom");

        tContrasenya1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tContrasenya1.setText("Contrasenya");

        aContrasenya1.setBackground(new java.awt.Color(204, 204, 255));
        aContrasenya1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aContrasenya1.setForeground(new java.awt.Color(153, 153, 153));
        aContrasenya1.setText("aaaaaaaaaaaaa");
        aContrasenya1.setBorder(null);
        aContrasenya1.setMaximumSize(new java.awt.Dimension(79, 1));
        aContrasenya1.setMinimumSize(new java.awt.Dimension(79, 1));
        aContrasenya1.setPreferredSize(new java.awt.Dimension(79, 1));
        aContrasenya1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aContrasenya1MousePressed(evt);
            }
        });
        aContrasenya1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aContrasenya1ActionPerformed(evt);
            }
        });

        bEnrere1.setBorderPainted(false);
        bEnrere1.setContentAreaFilled(false);
        bEnrere1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEnrere1.setMaximumSize(new java.awt.Dimension(50, 50));
        bEnrere1.setMinimumSize(new java.awt.Dimension(50, 50));
        bEnrere1.setPreferredSize(new java.awt.Dimension(50, 50));
        bEnrere1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnrere1ActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 2));

        aNom1.setBackground(new java.awt.Color(204, 204, 255));
        aNom1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aNom1.setForeground(new java.awt.Color(153, 153, 153));
        aNom1.setText("Introdueix el teu nom d'usuari");
        aNom1.setBorder(null);
        aNom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aNom1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPantalla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEnrere1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(bIniciarSessio2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tContrasenya1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tNom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aContrasenya1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aNom1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(bEnrere1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                .addGap(166, 166, 166)
                .addComponent(tNom1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aNom1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(81, 81, 81)
                .addComponent(tContrasenya1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aContrasenya1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(bIniciarSessio2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bIniciarSessio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarSessio2ActionPerformed
        // TODO add your handling code here:
        String nom = aNom1.getText();
        String contra = aContrasenya1.getText();
        if(nom.equals("Introdueix el teu nom d'usuari") || nom.contains(" ")) {
            JOptionPane.showMessageDialog(null, "Introdueix al teu nom d'usuari sense espais", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (contra.equals("aaaaaaaaaaaaa") || String.valueOf(aContrasenya1.getPassword()).isEmpty() || contra.contains(" ")){
            JOptionPane.showMessageDialog(null, "Introdueix la teva contrasenya sense espais", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            if(vistaPrincipal.existsUsuari(nom)){
                try {
                    vistaPrincipal.getUsuari(nom);
                    vistaPrincipal.verificarContra(contra);
                    
                    vistaPrincipal.setUsuari(nom);
                    vistaPrincipal.showPanel("JocView");
                } catch (Exception e){ 
                    JOptionPane.showMessageDialog(null, "Error al recuperar Usuari: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "L'usuari no existeix al sistema", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_bIniciarSessio2ActionPerformed

    private void aContrasenya1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aContrasenya1MousePressed
        // TODO add your handling code here:
    if(aContrasenya1.getText().equals("aaaaaaaaaaaaa")){
            aContrasenya1.setText("");
            aContrasenya1.setForeground(Color.black);
        }
        if(String.valueOf(aNom1.getText()).isEmpty()){
            aNom1.setText("Introdueix el teu nom d'usuari");
            aNom1.setForeground(Color.gray);
        }
    }//GEN-LAST:event_aContrasenya1MousePressed

    private void aContrasenya1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aContrasenya1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aContrasenya1ActionPerformed

    private void bEnrere1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnrere1ActionPerformed
        // TODO add your handling code here:
        vistaPrincipal.showPanel("MainView");
    }//GEN-LAST:event_bEnrere1ActionPerformed

    private void aNom1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aNom1MousePressed
        if(aNom1.getText().equals("Introdueix el teu nom d'usuari")){
            aNom1.setText("");
            aNom1.setForeground(Color.black);
        }
        if(String.valueOf(aContrasenya1.getPassword()).isEmpty()){
            aContrasenya1.setText("aaaaaaaaaaaaa");
            aContrasenya1.setForeground(Color.gray);
        }
    }//GEN-LAST:event_aNom1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField aContrasenya1;
    private javax.swing.JTextField aNom1;
    private javax.swing.JButton bEnrere1;
    private javax.swing.JButton bIniciarSessio2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel tContrasenya1;
    private javax.swing.JLabel tNom1;
    private javax.swing.JLabel tPantalla2;
    // End of variables declaration//GEN-END:variables
}
