/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes.presentacio;

import javax.swing.JPanel;


/**
 * Classe que representa la vista principal de l'aplicacio.
 *
 * @author marti
 */
public class MainView extends javax.swing.JPanel {
    
    private final PrincipalView vistaPrincipal; 
    /**
     * Crea una nova instancia de MainView i inicialitza els components.
     *
     * @param vistaPrincipal La vista principal de l'aplicacio.
     */
    public MainView(PrincipalView vistaPrincipal) {
        this.vistaPrincipal = vistaPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tPantalla = new javax.swing.JLabel();
        bcerrar = new javax.swing.JButton();
        bIniciarSessio = new javax.swing.JButton();
        bCrearSessio = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        tPantalla.setFont(new java.awt.Font("Segoe UI Black", 1, 70)); // NOI18N
        tPantalla.setForeground(new java.awt.Color(0, 102, 102));
        tPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPantalla.setText("KenKen");
        tPantalla.setAlignmentX(0.5F);
        tPantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tPantalla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bcerrar.setBackground(new java.awt.Color(204, 204, 255));
        bcerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bcerrar.setForeground(new java.awt.Color(255, 51, 51));
        bcerrar.setText("X");
        bcerrar.setBorder(null);
        bcerrar.setContentAreaFilled(false);
        bcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcerrarActionPerformed(evt);
            }
        });

        bIniciarSessio.setBackground(new java.awt.Color(0, 102, 102));
        bIniciarSessio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        bIniciarSessio.setForeground(new java.awt.Color(255, 255, 255));
        bIniciarSessio.setText("Iniciar Sessio");
        bIniciarSessio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bIniciarSessio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarSessioActionPerformed(evt);
            }
        });

        bCrearSessio.setBackground(new java.awt.Color(0, 102, 102));
        bCrearSessio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        bCrearSessio.setForeground(new java.awt.Color(255, 255, 255));
        bCrearSessio.setText("Crear Sessio");
        bCrearSessio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCrearSessio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearSessioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bCrearSessio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bIniciarSessio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(750, 750, 750)
                .addComponent(bcerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(82, 82, 82)
                .addComponent(bIniciarSessio, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(bCrearSessio, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcerrarActionPerformed

        vistaPrincipal.dispose();
        System.exit(0);
    }//GEN-LAST:event_bcerrarActionPerformed

    private void bIniciarSessioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarSessioActionPerformed
        vistaPrincipal.showPanel("IniciarSessioView");
    }//GEN-LAST:event_bIniciarSessioActionPerformed

    private void bCrearSessioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearSessioActionPerformed
        vistaPrincipal.showPanel("CrearSessioView");
    }//GEN-LAST:event_bCrearSessioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrearSessio;
    private javax.swing.JButton bIniciarSessio;
    private javax.swing.JButton bcerrar;
    private javax.swing.JLabel tPantalla;
    // End of variables declaration//GEN-END:variables
}
