/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes.presentacio;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 * Classe RankingView que representa la vista de classificacions del joc Kenken.
 * Aquesta classe es responsable de mostrar la classificacio dels jugadors.
 *
 * @author marti
 */
public class RankingView extends javax.swing.JPanel {
    private final PrincipalView vistaPrincipal; 
    
    public JLabel[] posiciones;
    public JLabel[] tiempos;
    public JLabel[] nombres;
    /**
     * Assigna una nova instancia de RankingView i inicialitza els components.
     *
     * @param vistaPrincipal La vista principal de l'aplicacio.
     */
    public RankingView(PrincipalView vistaPrincipal) {
        this.vistaPrincipal = vistaPrincipal;
        


        initComponents();
        
        ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("/images/flecha.png"));
        Image image = imageIcon.getImage(); // Convertir ImageIcon a Image
        Image newImage = image.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Escalar la imagen
        ImageIcon scaledImageIcon = new ImageIcon(newImage);
        bEnrere7.setIcon(scaledImageIcon);
        
        posiciones = new JLabel[]{tPos,tPos1,tPos2,tPos3,tPos4,tPos5,tPos6,tPos7,tPos8,tPos9};
        tiempos = new JLabel[]{tTemps,tTemps1,tTemps2,tTemps3,tTemps4,tTemps5,tTemps6,tTemps7,tTemps8,tTemps9};
        nombres = new JLabel[]{tNom1,tNom5,tNom6,tNom7,tNom8,tNom9,tNom10,tNom11,tNom12,tNom13};

    }
    
    public void ini(String Ranking,String nomJugador){
        if(vistaPrincipal.getIdPartida() == -1){ //ve de la pantalla de seleccio
            tPantalla6.setText("Ranking");
            bContinuar1.setVisible(false);
            bEnrere7.setVisible(true);
        }
        else{//acaba una partida
            tPantalla6.setText("Enhorabona!!!");
            bContinuar1.setVisible(true);
            bEnrere7.setVisible(false);
        }
        
        JsonObject RankingJSON = new Gson().fromJson(Ranking,JsonObject.class);
        
        JsonArray posicions = RankingJSON.getAsJsonArray("rankings");
        
        Boolean trobat = false;
        
        Integer mida = posicions.size();
        if(mida > 10) mida = 10;
        
        for (Integer i = 0; i < mida; ++i) {
            posiciones[i].setFont(new java.awt.Font("Segoe UI Semibold", 0, 18));
            tiempos[i].setFont(new java.awt.Font("Segoe UI", 0, 14));
            nombres[i].setFont(new java.awt.Font("Segoe UI", 0, 14));
            JsonObject posicio = posicions.get(i).getAsJsonObject();
            String pos = String.valueOf(i+1);
            String temps = posicio.has("tiempo") ? posicio.get("tiempo").getAsString() : "NULL";
            String nom = posicio.has("username") ? posicio.get("username").getAsString() : "NULL";

            
            posiciones[i].setText(pos);
            tiempos[i].setText(temps);
            nombres[i].setText(nom);
            if(nom.equals( nomJugador)){
                trobat = true;
                posiciones[i].setFont(new java.awt.Font("Segoe UI Semibold", 1, 18));
                tiempos[i].setFont(new java.awt.Font("Segoe UI", 1, 14));
                nombres[i].setFont(new java.awt.Font("Segoe UI", 1, 14));
            }
            
        }
        
        if(trobat == false){
            String[] info= vistaPrincipal.getInfoRanking(vistaPrincipal.getIdKenken(),nomJugador);
            if(info != null){
                posiciones[8].setText("...");
                tiempos[8].setText("...");
                nombres[8].setText("...");
                
                posiciones[9].setFont(new java.awt.Font("Segoe UI Semibold", 1, 18));
                tiempos[9].setFont(new java.awt.Font("Segoe UI", 1, 14));
                nombres[9].setFont(new java.awt.Font("Segoe UI", 1, 14));
                
                posiciones[9].setText(info[0]);
                tiempos[9].setText(info[1]);
                nombres[9].setText(nomJugador);
            }   

        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tPantalla6 = new javax.swing.JLabel();
        bContinuar1 = new javax.swing.JButton();
        Pranking1 = new javax.swing.JPanel();
        instancia_rank = new javax.swing.JPanel();
        aux4 = new javax.swing.JPanel();
        tPos = new javax.swing.JLabel();
        tTemps = new javax.swing.JLabel();
        tNom1 = new javax.swing.JLabel();
        instancia_rank1 = new javax.swing.JPanel();
        aux5 = new javax.swing.JPanel();
        tPos1 = new javax.swing.JLabel();
        tTemps1 = new javax.swing.JLabel();
        tNom5 = new javax.swing.JLabel();
        instancia_rank2 = new javax.swing.JPanel();
        aux6 = new javax.swing.JPanel();
        tPos2 = new javax.swing.JLabel();
        tTemps2 = new javax.swing.JLabel();
        tNom6 = new javax.swing.JLabel();
        instancia_rank3 = new javax.swing.JPanel();
        aux7 = new javax.swing.JPanel();
        tPos3 = new javax.swing.JLabel();
        tTemps3 = new javax.swing.JLabel();
        tNom7 = new javax.swing.JLabel();
        instancia_rank4 = new javax.swing.JPanel();
        aux8 = new javax.swing.JPanel();
        tPos4 = new javax.swing.JLabel();
        tTemps4 = new javax.swing.JLabel();
        tNom8 = new javax.swing.JLabel();
        instancia_rank5 = new javax.swing.JPanel();
        aux9 = new javax.swing.JPanel();
        tPos5 = new javax.swing.JLabel();
        tTemps5 = new javax.swing.JLabel();
        tNom9 = new javax.swing.JLabel();
        instancia_rank6 = new javax.swing.JPanel();
        aux10 = new javax.swing.JPanel();
        tPos6 = new javax.swing.JLabel();
        tTemps6 = new javax.swing.JLabel();
        tNom10 = new javax.swing.JLabel();
        instancia_rank7 = new javax.swing.JPanel();
        aux11 = new javax.swing.JPanel();
        tPos7 = new javax.swing.JLabel();
        tTemps7 = new javax.swing.JLabel();
        tNom11 = new javax.swing.JLabel();
        instancia_rank8 = new javax.swing.JPanel();
        aux12 = new javax.swing.JPanel();
        tPos8 = new javax.swing.JLabel();
        tTemps8 = new javax.swing.JLabel();
        tNom12 = new javax.swing.JLabel();
        instancia_rank9 = new javax.swing.JPanel();
        aux13 = new javax.swing.JPanel();
        tPos9 = new javax.swing.JLabel();
        tTemps9 = new javax.swing.JLabel();
        tNom13 = new javax.swing.JLabel();
        bEnrere7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        tPantalla6.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        tPantalla6.setForeground(new java.awt.Color(0, 102, 102));
        tPantalla6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPantalla6.setText("Enhorabona!!!");

        bContinuar1.setBackground(new java.awt.Color(0, 102, 102));
        bContinuar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        bContinuar1.setForeground(new java.awt.Color(255, 255, 255));
        bContinuar1.setText("Continuar");
        bContinuar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bContinuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContinuar1ActionPerformed(evt);
            }
        });

        Pranking1.setBackground(new java.awt.Color(153, 153, 153));
        Pranking1.setLayout(new java.awt.GridLayout(10, 0));

        instancia_rank.setLayout(new java.awt.GridLayout(1, 2));

        aux4.setLayout(new java.awt.GridLayout(1, 0));

        tPos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux4.add(tPos);

        tTemps.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps.setToolTipText("");
        aux4.add(tTemps);

        instancia_rank.add(aux4);

        tNom1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom1.setToolTipText("");
        instancia_rank.add(tNom1);

        Pranking1.add(instancia_rank);

        instancia_rank1.setLayout(new java.awt.GridLayout(1, 2));

        aux5.setLayout(new java.awt.GridLayout(1, 0));

        tPos1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos1.setToolTipText("");
        tPos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux5.add(tPos1);

        tTemps1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps1.setToolTipText("");
        aux5.add(tTemps1);

        instancia_rank1.add(aux5);

        tNom5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom5.setToolTipText("");
        instancia_rank1.add(tNom5);

        Pranking1.add(instancia_rank1);

        instancia_rank2.setLayout(new java.awt.GridLayout(1, 2));

        aux6.setLayout(new java.awt.GridLayout(1, 0));

        tPos2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos2.setToolTipText("");
        tPos2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux6.add(tPos2);

        tTemps2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps2.setToolTipText("");
        aux6.add(tTemps2);

        instancia_rank2.add(aux6);

        tNom6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom6.setToolTipText("");
        instancia_rank2.add(tNom6);

        Pranking1.add(instancia_rank2);

        instancia_rank3.setLayout(new java.awt.GridLayout(1, 2));

        aux7.setLayout(new java.awt.GridLayout(1, 0));

        tPos3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos3.setToolTipText("");
        tPos3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux7.add(tPos3);

        tTemps3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps3.setToolTipText("");
        aux7.add(tTemps3);

        instancia_rank3.add(aux7);

        tNom7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom7.setToolTipText("");
        instancia_rank3.add(tNom7);

        Pranking1.add(instancia_rank3);

        instancia_rank4.setLayout(new java.awt.GridLayout(1, 2));

        aux8.setLayout(new java.awt.GridLayout(1, 0));

        tPos4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos4.setToolTipText("");
        tPos4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux8.add(tPos4);

        tTemps4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps4.setToolTipText("");
        aux8.add(tTemps4);

        instancia_rank4.add(aux8);

        tNom8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom8.setToolTipText("");
        instancia_rank4.add(tNom8);

        Pranking1.add(instancia_rank4);

        instancia_rank5.setLayout(new java.awt.GridLayout(1, 2));

        aux9.setLayout(new java.awt.GridLayout(1, 0));

        tPos5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos5.setToolTipText("");
        tPos5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux9.add(tPos5);

        tTemps5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps5.setToolTipText("");
        aux9.add(tTemps5);

        instancia_rank5.add(aux9);

        tNom9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom9.setToolTipText("");
        instancia_rank5.add(tNom9);

        Pranking1.add(instancia_rank5);

        instancia_rank6.setLayout(new java.awt.GridLayout(1, 2));

        aux10.setLayout(new java.awt.GridLayout(1, 0));

        tPos6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos6.setToolTipText("");
        tPos6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux10.add(tPos6);

        tTemps6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps6.setToolTipText("");
        aux10.add(tTemps6);

        instancia_rank6.add(aux10);

        tNom10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom10.setToolTipText("");
        instancia_rank6.add(tNom10);

        Pranking1.add(instancia_rank6);

        instancia_rank7.setLayout(new java.awt.GridLayout(1, 2));

        aux11.setLayout(new java.awt.GridLayout(1, 0));

        tPos7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos7.setToolTipText("");
        tPos7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux11.add(tPos7);

        tTemps7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps7.setToolTipText("");
        aux11.add(tTemps7);

        instancia_rank7.add(aux11);

        tNom11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom11.setToolTipText("");
        instancia_rank7.add(tNom11);

        Pranking1.add(instancia_rank7);

        instancia_rank8.setLayout(new java.awt.GridLayout(1, 2));

        aux12.setLayout(new java.awt.GridLayout(1, 0));

        tPos8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos8.setToolTipText("");
        tPos8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux12.add(tPos8);

        tTemps8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps8.setToolTipText("");
        aux12.add(tTemps8);

        instancia_rank8.add(aux12);

        tNom12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom12.setToolTipText("");
        instancia_rank8.add(tNom12);

        Pranking1.add(instancia_rank8);

        instancia_rank9.setLayout(new java.awt.GridLayout(1, 2));

        aux13.setLayout(new java.awt.GridLayout(1, 0));

        tPos9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tPos9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPos9.setToolTipText("");
        tPos9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aux13.add(tPos9);

        tTemps9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tTemps9.setToolTipText("");
        aux13.add(tTemps9);

        instancia_rank9.add(aux13);

        tNom13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNom13.setToolTipText("");
        instancia_rank9.add(tNom13);

        Pranking1.add(instancia_rank9);

        bEnrere7.setBorderPainted(false);
        bEnrere7.setContentAreaFilled(false);
        bEnrere7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEnrere7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnrere7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Pranking1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tPantalla6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bEnrere7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(450, 450, 450))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(bContinuar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(bEnrere7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPantalla6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(Pranking1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bContinuar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bContinuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContinuar1ActionPerformed
        // TODO add your handling code here:
        
        vistaPrincipal.showPanel("JocView");
    }//GEN-LAST:event_bContinuar1ActionPerformed

    private void bEnrere7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnrere7ActionPerformed
        // TODO add your handling code here:
        vistaPrincipal.setIdKenken(-1);
        vistaPrincipal.showPanel("Seleccio2View");
    }//GEN-LAST:event_bEnrere7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pranking1;
    private javax.swing.JPanel aux10;
    private javax.swing.JPanel aux11;
    private javax.swing.JPanel aux12;
    private javax.swing.JPanel aux13;
    private javax.swing.JPanel aux4;
    private javax.swing.JPanel aux5;
    private javax.swing.JPanel aux6;
    private javax.swing.JPanel aux7;
    private javax.swing.JPanel aux8;
    private javax.swing.JPanel aux9;
    private javax.swing.JButton bContinuar1;
    private javax.swing.JButton bEnrere7;
    private javax.swing.JPanel instancia_rank;
    private javax.swing.JPanel instancia_rank1;
    private javax.swing.JPanel instancia_rank2;
    private javax.swing.JPanel instancia_rank3;
    private javax.swing.JPanel instancia_rank4;
    private javax.swing.JPanel instancia_rank5;
    private javax.swing.JPanel instancia_rank6;
    private javax.swing.JPanel instancia_rank7;
    private javax.swing.JPanel instancia_rank8;
    private javax.swing.JPanel instancia_rank9;
    private javax.swing.JLabel tNom1;
    private javax.swing.JLabel tNom10;
    private javax.swing.JLabel tNom11;
    private javax.swing.JLabel tNom12;
    private javax.swing.JLabel tNom13;
    private javax.swing.JLabel tNom5;
    private javax.swing.JLabel tNom6;
    private javax.swing.JLabel tNom7;
    private javax.swing.JLabel tNom8;
    private javax.swing.JLabel tNom9;
    private javax.swing.JLabel tPantalla6;
    private javax.swing.JLabel tPos;
    private javax.swing.JLabel tPos1;
    private javax.swing.JLabel tPos2;
    private javax.swing.JLabel tPos3;
    private javax.swing.JLabel tPos4;
    private javax.swing.JLabel tPos5;
    private javax.swing.JLabel tPos6;
    private javax.swing.JLabel tPos7;
    private javax.swing.JLabel tPos8;
    private javax.swing.JLabel tPos9;
    private javax.swing.JLabel tTemps;
    private javax.swing.JLabel tTemps1;
    private javax.swing.JLabel tTemps2;
    private javax.swing.JLabel tTemps3;
    private javax.swing.JLabel tTemps4;
    private javax.swing.JLabel tTemps5;
    private javax.swing.JLabel tTemps6;
    private javax.swing.JLabel tTemps7;
    private javax.swing.JLabel tTemps8;
    private javax.swing.JLabel tTemps9;
    // End of variables declaration//GEN-END:variables
}
